services:
  myfood:
    build: .
    image: myfood-web
    container_name: myfood-web
    environment:
      PORT: 80
      DATABASE_URL: ${DATABASE_URL}
      COS_SECRET_ID: ${COS_SECRET_ID}
      COS_SECRET_KEY: ${COS_SECRET_KEY}
      COS_REGION: ${COS_REGION}
      COS_BUCKET: ${COS_BUCKET}
    ports:
      - "8080:80"
    restart: unless-stopped
